package app.calendarium.core.ui.theme

import androidx.compose.ui.graphics.Color

// Seed-derived primary. Real palette is generated by Material 3 (dynamic or fallback).
val CalendariumBlue = Color(0xFF1976D2)
val CalendariumBlueDark = Color(0xFF8AB4F8)
