package app.foscal.core.model

/**
 * Windows time zone names mapped to the IANA zone CLDR picks for the "001" territory.
 *
 * Outlook and Exchange write these names as TZIDs (`W. Europe Standard Time`). Generated from
 * CLDR's `windowsZones` data as shipped in ICU4J 77.1 (Unicode licence). It is a table here, not
 * `android.icu.util.TimeZone.getIDForWindowsID`, so that `:core-model` stays plain JVM and the
 * `.ics` reader can be tested without a device.
 */
internal val WINDOWS_ZONES: Map<String, String> = mapOf(
    "AUS Central Standard Time" to "Australia/Darwin",
    "AUS Eastern Standard Time" to "Australia/Sydney",
    "Afghanistan Standard Time" to "Asia/Kabul",
    "Alaskan Standard Time" to "America/Anchorage",
    "Aleutian Standard Time" to "America/Adak",
    "Altai Standard Time" to "Asia/Barnaul",
    "Arab Standard Time" to "Asia/Riyadh",
    "Arabian Standard Time" to "Asia/Dubai",
    "Arabic Standard Time" to "Asia/Baghdad",
    "Argentina Standard Time" to "America/Buenos_Aires",
    "Astrakhan Standard Time" to "Europe/Astrakhan",
    "Atlantic Standard Time" to "America/Halifax",
    "Aus Central W. Standard Time" to "Australia/Eucla",
    "Azerbaijan Standard Time" to "Asia/Baku",
    "Azores Standard Time" to "Atlantic/Azores",
    "Bahia Standard Time" to "America/Bahia",
    "Bangladesh Standard Time" to "Asia/Dhaka",
    "Belarus Standard Time" to "Europe/Minsk",
    "Bougainville Standard Time" to "Pacific/Bougainville",
    "Canada Central Standard Time" to "America/Regina",
    "Cape Verde Standard Time" to "Atlantic/Cape_Verde",
    "Caucasus Standard Time" to "Asia/Yerevan",
    "Cen. Australia Standard Time" to "Australia/Adelaide",
    "Central America Standard Time" to "America/Guatemala",
    "Central Asia Standard Time" to "Asia/Bishkek",
    "Central Brazilian Standard Time" to "America/Cuiaba",
    "Central Europe Standard Time" to "Europe/Budapest",
    "Central European Standard Time" to "Europe/Warsaw",
    "Central Pacific Standard Time" to "Pacific/Guadalcanal",
    "Central Standard Time" to "America/Chicago",
    "Central Standard Time (Mexico)" to "America/Mexico_City",
    "Chatham Islands Standard Time" to "Pacific/Chatham",
    "China Standard Time" to "Asia/Shanghai",
    "Cuba Standard Time" to "America/Havana",
    "Dateline Standard Time" to "Etc/GMT+12",
    "E. Africa Standard Time" to "Africa/Nairobi",
    "E. Australia Standard Time" to "Australia/Brisbane",
    "E. Europe Standard Time" to "Europe/Chisinau",
    "E. South America Standard Time" to "America/Sao_Paulo",
    "Easter Island Standard Time" to "Pacific/Easter",
    "Eastern Standard Time" to "America/New_York",
    "Eastern Standard Time (Mexico)" to "America/Cancun",
    "Egypt Standard Time" to "Africa/Cairo",
    "Ekaterinburg Standard Time" to "Asia/Yekaterinburg",
    "FLE Standard Time" to "Europe/Kiev",
    "Fiji Standard Time" to "Pacific/Fiji",
    "GMT Standard Time" to "Europe/London",
    "GTB Standard Time" to "Europe/Bucharest",
    "Georgian Standard Time" to "Asia/Tbilisi",
    "Greenland Standard Time" to "America/Godthab",
    "Greenwich Standard Time" to "Atlantic/Reykjavik",
    "Haiti Standard Time" to "America/Port-au-Prince",
    "Hawaiian Standard Time" to "Pacific/Honolulu",
    "India Standard Time" to "Asia/Calcutta",
    "Iran Standard Time" to "Asia/Tehran",
    "Israel Standard Time" to "Asia/Jerusalem",
    "Jordan Standard Time" to "Asia/Amman",
    "Kaliningrad Standard Time" to "Europe/Kaliningrad",
    "Korea Standard Time" to "Asia/Seoul",
    "Libya Standard Time" to "Africa/Tripoli",
    "Line Islands Standard Time" to "Pacific/Kiritimati",
    "Lord Howe Standard Time" to "Australia/Lord_Howe",
    "Magadan Standard Time" to "Asia/Magadan",
    "Magallanes Standard Time" to "America/Punta_Arenas",
    "Marquesas Standard Time" to "Pacific/Marquesas",
    "Mauritius Standard Time" to "Indian/Mauritius",
    "Middle East Standard Time" to "Asia/Beirut",
    "Montevideo Standard Time" to "America/Montevideo",
    "Morocco Standard Time" to "Africa/Casablanca",
    "Mountain Standard Time" to "America/Denver",
    "Mountain Standard Time (Mexico)" to "America/Mazatlan",
    "Myanmar Standard Time" to "Asia/Rangoon",
    "N. Central Asia Standard Time" to "Asia/Novosibirsk",
    "Namibia Standard Time" to "Africa/Windhoek",
    "Nepal Standard Time" to "Asia/Katmandu",
    "New Zealand Standard Time" to "Pacific/Auckland",
    "Newfoundland Standard Time" to "America/St_Johns",
    "Norfolk Standard Time" to "Pacific/Norfolk",
    "North Asia East Standard Time" to "Asia/Irkutsk",
    "North Asia Standard Time" to "Asia/Krasnoyarsk",
    "North Korea Standard Time" to "Asia/Pyongyang",
    "Omsk Standard Time" to "Asia/Omsk",
    "Pacific SA Standard Time" to "America/Santiago",
    "Pacific Standard Time" to "America/Los_Angeles",
    "Pacific Standard Time (Mexico)" to "America/Tijuana",
    "Pakistan Standard Time" to "Asia/Karachi",
    "Paraguay Standard Time" to "America/Asuncion",
    "Qyzylorda Standard Time" to "Asia/Qyzylorda",
    "Romance Standard Time" to "Europe/Paris",
    "Russia Time Zone 10" to "Asia/Srednekolymsk",
    "Russia Time Zone 11" to "Asia/Kamchatka",
    "Russia Time Zone 3" to "Europe/Samara",
    "Russian Standard Time" to "Europe/Moscow",
    "SA Eastern Standard Time" to "America/Cayenne",
    "SA Pacific Standard Time" to "America/Bogota",
    "SA Western Standard Time" to "America/La_Paz",
    "SE Asia Standard Time" to "Asia/Bangkok",
    "Saint Pierre Standard Time" to "America/Miquelon",
    "Sakhalin Standard Time" to "Asia/Sakhalin",
    "Samoa Standard Time" to "Pacific/Apia",
    "Sao Tome Standard Time" to "Africa/Sao_Tome",
    "Saratov Standard Time" to "Europe/Saratov",
    "Singapore Standard Time" to "Asia/Singapore",
    "South Africa Standard Time" to "Africa/Johannesburg",
    "South Sudan Standard Time" to "Africa/Juba",
    "Sri Lanka Standard Time" to "Asia/Colombo",
    "Sudan Standard Time" to "Africa/Khartoum",
    "Syria Standard Time" to "Asia/Damascus",
    "Taipei Standard Time" to "Asia/Taipei",
    "Tasmania Standard Time" to "Australia/Hobart",
    "Tocantins Standard Time" to "America/Araguaina",
    "Tokyo Standard Time" to "Asia/Tokyo",
    "Tomsk Standard Time" to "Asia/Tomsk",
    "Tonga Standard Time" to "Pacific/Tongatapu",
    "Transbaikal Standard Time" to "Asia/Chita",
    "Turkey Standard Time" to "Europe/Istanbul",
    "Turks And Caicos Standard Time" to "America/Grand_Turk",
    "US Eastern Standard Time" to "America/Indianapolis",
    "US Mountain Standard Time" to "America/Phoenix",
    "UTC" to "Etc/UTC",
    "UTC+12" to "Etc/GMT-12",
    "UTC+13" to "Etc/GMT-13",
    "UTC-02" to "Etc/GMT+2",
    "UTC-08" to "Etc/GMT+8",
    "UTC-09" to "Etc/GMT+9",
    "UTC-11" to "Etc/GMT+11",
    "Ulaanbaatar Standard Time" to "Asia/Ulaanbaatar",
    "Venezuela Standard Time" to "America/Caracas",
    "Vladivostok Standard Time" to "Asia/Vladivostok",
    "Volgograd Standard Time" to "Europe/Volgograd",
    "W. Australia Standard Time" to "Australia/Perth",
    "W. Central Africa Standard Time" to "Africa/Lagos",
    "W. Europe Standard Time" to "Europe/Berlin",
    "W. Mongolia Standard Time" to "Asia/Hovd",
    "West Asia Standard Time" to "Asia/Tashkent",
    "West Bank Standard Time" to "Asia/Hebron",
    "West Pacific Standard Time" to "Pacific/Port_Moresby",
    "Yakutsk Standard Time" to "Asia/Yakutsk",
    "Yukon Standard Time" to "America/Whitehorse",
)
